name: Deploy SvelteKit Site to GitHub Pages

on:
  # main 브랜치에 푸시될 때마다 실행됩니다.
  push:
    branches:
      - main
  # GitHub Actions 탭에서 수동으로 실행할 수도 있게 합니다.
  workflow_dispatch:

# Actions가 GITHUB_TOKEN을 사용하여 GitHub Pages에 배포할 수 있도록 권한을 설정합니다.
permissions:
  contents: read
  pages: write
  id-token: write

# 한 번에 하나의 배포만 실행되도록 동시성 설정을 합니다.
# 동일한 그룹에 대한 새 워크플로우 실행 시 이전 실행은 취소됩니다.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4 # pnpm/action-setup 액션의 최신 버전을 확인하는 것도 좋습니다.
        with:
          version: 10 # 요청하신 pnpm 버전 10으로 변경

      - name: Setup Node.js
        uses: actions/setup-node@v4 # actions/setup-node 액션의 최신 버전을 확인하는 것도 좋습니다.
        with:
          node-version: "22" # 요청하신 Node.js 버전 22로 변경
          cache: "pnpm" # pnpm 의존성 캐싱

      - name: Install dependencies (frontend)
        working-directory: ./frontend # frontend 폴더로 이동하여 명령어 실행
        run: pnpm install

      - name: Build SvelteKit site (frontend)
        working-directory: ./frontend # frontend 폴더로 이동하여 명령어 실행
        run: pnpm run build # SvelteKit 빌드 명령 (adapter-static 필요)

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
        # SvelteKit의 adapter-static이 `base` 경로를 자동으로 처리하므로
        # 이 Action에서 base path를 별도로 설정할 필요가 없을 수 있습니다.
        # 만약 username.github.io가 아닌 username.github.io/repo-name 형태라면
        # SvelteKit의 paths.base 설정이 중요합니다.

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # SvelteKit의 adapter-static에서 설정한 빌드 출력 폴더 경로를 지정합니다.
          # 기본적으로 'build' 폴더입니다. frontend 폴더 내의 경로로 지정해야 합니다.
          path: ./frontend/build

  deploy:
    needs: build # build 작업이 성공해야 실행됨
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # 배포된 사이트 URL을 출력
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
